## Assiginment_8 python programming (basics)

###### 1.Write a Python Program to add two  matrices?

In [19]:
# A basic code for matrix input from user
R = int(input("Enter the number of rows of first matrix:"))
C = int(input("Enter the number of columns of first matrix:"))
# Initialize matrix
X = []
print("Enter the entries rowwise:")
# For user input
for i in range(R):		 # A for loop for row entries
	a =[]
	for j in range(C):	 # A for loop for column entries
		a.append(int(input()))
	X.append(a)
# For printing the matrix
R1 = int(input("Enter the number of rows of second matrix:"))
C1 = int(input("Enter the number of columns of second matrix:"))
# Initialize matrix
Y = []
print("Enter the entries rowwise:")
# For user input
for i in range(R1):		 # A for loop for row entries
	a =[]
	for j in range(C1):	 # A for loop for column entries
		a.append(int(input()))
	Y.append(a)
# For printing the matrix
if R==R1 and C==C1:
    result = [[X[i][j] + Y[i][j]  for j in range(len(X[0]))] for i in range(len(X))]
    for r in result:
        print(r)
else:print("invalid dimensions")

Enter the number of rows of first matrix:2
Enter the number of columns of first matrix:3
Enter the entries rowwise:
1
2
3
4
5
6
Enter the number of rows of second matrix:2
Enter the number of columns of second matrix:3
Enter the entries rowwise:
7
8
9
10
11
12
[8, 10, 12]
[14, 16, 18]


`or`

In [18]:
import numpy as np
try:
    a=int(input("no of rows"))
    b=int(input("no of columns"))
    c=list(map(int,input().split()))
    d=np.array(c).reshape(a,b)
    print(d)
    e=int(input("no of rows in second matrix"))
    f=int(input("no of columns in second matrix"))
    g=list(map(int,input().split()))
    h=np.array(g).reshape(e,f)
    print(h)
    if a==e and b==f:
        x=np.add(d,h)
        print("output matrix is")
        print(x)
    else:
        print("invalid dimension")
except Exception as e:
              print(e)

no of rows2
no of columns3
1 2 3 4 5 6
[[1 2 3]
 [4 5 6]]
no of rows in second matrix2
no of columns in second matrix3
7 8 9 10 11 12
[[ 7  8  9]
 [10 11 12]]
output matrix is
[[ 8 10 12]
 [14 16 18]]


###### Write a Python Program to multiply two matrices?

In [2]:
import numpy as np
try:
    a=int(input("no of rows"))
    b=int(input("no of columns"))
    c=list(map(int,input().split()))
    d=np.array(c).reshape(a,b)
    print(d)
    e=int(input("no of rows in second matrix"))
    f=int(input("no of columns in second matrix"))
    g=list(map(int,input().split()))
    h=np.array(g).reshape(e,f)
    print(h)
    if a==b==e==f:
        x=np.dot(d,h)
        print("output matrix is")
        for r in range(len(x)):
            for c in range(len(x[0])):
                print(x[r][c],end=" ")
            print()
    else:
        print("invalid dimension")
except Exception as e:
              print(e)

no of rows3
no of columns3
1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
no of rows in second matrix3
no of columns in second matrix3
10 11 12 13 14 15 16 17 18
[[10 11 12]
 [13 14 15]
 [16 17 18]]
output matrix is
84 90 96 
201 216 231 
318 342 366 


###### 3.Write a Python Program to Transpose a Matrix?

In [12]:
import numpy as np
try:
    a=int(input("no of rows"))
    b=int(input("no of columns"))
    c=list(map(int,input().split()))
    d=np.array(c).reshape(a,b)
    print("the matrix before transpose is")
    for r in range(len(d)):
            for c in range(len(d[0])):
                print(d[r][c],end=" ")
            print()
    a=[[0 for x in range(a)]for j in range(b)]
    for i in range(len(d[0])):
        for j in range(len(d)):
            a[i][j]=d[j][i]
    for r in range(len(a)):
        for c in range(len(a[0])):
            print(a[r][c],end=" ")
        print()
except Exception as e:
    print(e)

no of rows2
no of columns4
1 2 3 4 5 6 7 8
the matrix before transpose is
1 2 3 4 
5 6 7 8 
1 5 
2 6 
3 7 
4 8 


###### 4.Write a Python Program to Sort Words in Alphabetic Order?

In [3]:
a=input(" enter a string:")
b=[x.lower() for x in a.split()]
b.sort()
for a in b:
    print(a,end=" ")

 enter a string:Hello hi How are you doing!
are doing! hello hi how you 

###### 5.Write a Python Program to Remove Punctuation From a String?

In [8]:
a=input(" enter a string:")
pun="""!()-[]{};:'"\,<>./?@#$%^&*_~"""
for i in a:
    if i in pun:
        a=a.replace(i,"")
print(a)

 enter a string:Hello! How are you?
Hello How are you
